### ISSUE TITLE
Unescaped characters in XML paylod can lead to exceptions during record/replay.

### ISSUE THREAD

**Issue by MPA-rockIT** [rockitconsulting/test.rockitizer#46]
Unescaped characters e.g '&' in XML paylod can lead to exceptions during record/replay:

`INFO # <DummyTest>: Assertion
   INFO #############################################################################
  [Fatal Error] 0.txt:4:24: The entity name must immediately follow the '&' in the entity reference.
  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.108 sec <<< FAILURE!
  testDummy(DummyTest)  Time elapsed: 3.108 sec  <<< ERROR!
  org.xmlunit.XMLUnitException: The entity name must immediately follow the '&' in the entity reference.
	  at org.xmlunit.util.Convert.toDocument(Convert.java:144)
	  at org.xmlunit.util.Convert.toDocument(Convert.java:104)
	  at org.xmlunit.input.WhitespaceNormalizedSource.<init>(WhitespaceNormalizedSource.java:32)
	  at org.xmlunit.builder.DiffBuilder.wrap(DiffBuilder.java:355)
	  at org.xmlunit.builder.DiffBuilder.build(DiffBuilder.java:341)
	  at com.rockit.common.blackboxtester.assertions.XMLFileAssertion.build(XMLFileAssertion.java:130)
	  at com.rockit.common.blackboxtester.assertions.XMLFileAssertion.proceed(XMLFileAssertion.java:93)
	  at com.rockit.common.blackboxtester.suite.structures.TestBuilder.proceedAssertions(TestBuilder.java:66)
	  at com.rockit.common.blackboxtester.wrapper.AbstractTestWrapper.postProcess(AbstractTestWrapper.java:72)
	  at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	  at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
  Caused by: org.xml.sax.SAXParseException; systemId: file:/var/lib/jenkins/workspace/demo/demo.rockitizer/target/replay/DummyTest/output/020MQGetMessageFromMockQueue/MQGET.TEST_A_FROM_B_ADAPTER/0.txt; lineNumber: 4; columnNumber: 24; The entity name must immediately follow the '&' in the entity reference.
	  at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	  at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	  at org.xmlunit.util.Convert.toDocument(Convert.java:142)
	  ... 36 more`

**Comment by yefymdmukh** [comment]
Fix in test.rockitizer-1.0.5.10


correlationId and messageId in MQ Connector now being escaped to prevent creation of malformed xml structure
